#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later

readonly nmcli="$(nmcli c|tail +2|grep -v -- --)"
readonly uplink="$(<<< $nmcli egrep '(wifi|ethernet)'|cut -d' ' -f1)"
readonly vpn="$(<<< $nmcli grep wireguard|cut -d' ' -f1)"

if [ -n "$uplink" ]; then
    echo -n "<active>🌍︎ $uplink</active>"
else
    echo -n "<error>🌍︎ uplink</error>"
fi

echo -n ' '
if [ -n "$vpn" ]; then
    echo -n "<active>🔒︎$vpn</active>"
else
    echo -n '🔓︎ VPN'
fi

echo
exit 0
