#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# usage: $ block-mumble mumble.example.com 64738

set -euo pipefail

[ -z "${1:-}" ] && exit 1

readonly prog='"🎤︎ \(.users)/\(.users_max)"'
readonly reply="$(mumble-ping --json "$1" "${2:-64738}")"

[ -z "$reply" ] && { echo '<error>unknown<error>';  exit 0; }
jq -r '"🎤︎ \(.users)/\(.users_max)"' <<< "$reply"
