#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# depends: nmcli

readonly nmcli="$(nmcli c|tail +2|grep -v -- --)"
readonly vpn="$(<<< "$nmcli" grep -E '(wireguard|vpn)'|tr -s ' '|rev|cut -d' ' -f5-|rev)"

if [ -n "$vpn" ]; then
    echo -n "<active>🔒︎${vpn}</active>"
else
    echo -n '🔓︎ VPN'
fi

echo
exit 0
