#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-3.0-or-later
# depends: pulsemixer mpc

export MPD_HOST=/run/mpd:6600

readonly pulse_mute="$(pulsemixer --get-mute)"
readonly pulse_volume="$(pulsemixer --get-volume)"
readonly pulse_input_count="$(pulsemixer --list-sinks|grep input|wc -l)"

readonly mpd_state="$(mpc status)"

if [ -n "$pulse_volume" ]; then
    [ "$pulse_input_count" -gt 0 ] && echo -n '<active>'
    [ "$pulse_mute" = 0 ] && echo -n '🔉︎ ' || echo -n '<warning>🔇︎ '
    echo -n "${pulse_volume:0:2}%"
    [ "$pulse_mute" = 1 ] && echo -n '</warning>'
    [ "$pulse_input_count" -gt 0 ] && echo -n '</active>'
fi

if [ "$(<<< "$mpd_state" tail -1|cut -d' ' -f2)" != 'n/a' ]; then
    <<< "$mpd_state" grep -q '\[playing\]' && echo -n ' <active>'
    echo -n "♫ $(<<< "$mpd_state" tail -1|awk '{print $2}')"
    <<< "$mpd_state" grep -q '\[playing\]' && echo -n '</active>'
fi

echo
exit 0
